import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import type { EmailOtpType } from '@supabase/supabase-js';

// Allowed redirect paths — must start with / and not contain protocol or double-slash
function isSafeRedirectPath(path: string): boolean {
  return (
    typeof path === 'string' && path.startsWith('/') &&
    !path.startsWith('//') &&
    !path.includes(':')
  );
}

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url);

  const code = searchParams.get('code');
  const tokenHash = searchParams.get('token_hash');
  const type = searchParams.get('type') as EmailOtpType | null;
  const nextParam = searchParams.get('next') ?? '/cuenta';

  // Validate the redirect target to prevent open redirect attacks
  const next = isSafeRedirectPath(nextParam) ? nextParam : '/cuenta';

  const supabase = await createClient();

  // ── Path A: token_hash flow (used by generateLink / action_link) ──────────
  // When the user clicks the confirmation link generated by admin.generateLink(),
  // Supabase redirects to redirectTo with ?token_hash=...&type=signup
  // This MUST be consumed via verifyOtp — NOT exchangeCodeForSession.
  if (tokenHash && type) {
    const { error } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type });

    if (!error) {
      return NextResponse.redirect(`${origin}${next}`);
    }

    // Token invalid or already used
    if (next === '/email-verificado') {
      return NextResponse.redirect(`${origin}/verificar-email?error=enlace-invalido`);
    }
    return NextResponse.redirect(`${origin}/iniciar-sesion?error=enlace-invalido`);
  }

  // ── Path B: PKCE code flow (OAuth, magic link, password reset) ────────────
  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error) {
      return NextResponse.redirect(`${origin}${next}`);
    }

    if (next === '/email-verificado') {
      return NextResponse.redirect(`${origin}/verificar-email?error=enlace-invalido`);
    }
  }

  // Fallback — no valid params
  return NextResponse.redirect(`${origin}/iniciar-sesion?error=enlace-invalido`);
}
